name: megaspice
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flow_builder: ^0.0.6
  http: ^0.13.4
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  font_awesome_flutter: ^9.2.0
  formz: ^0.4.1
  shared_preferences: ^2.0.9
  bot_toast: ^4.0.1
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  firebase_storage: ^10.2.5
  firebase_dynamic_links: ^4.0.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  uuid: ^3.0.5
  cached_network_image: ^3.2.0
  timeago: ^3.1.0
  intl: ^0.17.0
  flutter_signin_button: ^2.0.0
  date_time_picker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/onboarding/